#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-netrc
Version  : 0.10.3
Release  : 4
URL      : https://rubygems.org/downloads/netrc-0.10.3.gem
Source0  : https://rubygems.org/downloads/netrc-0.10.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit
BuildRequires : rubygem-turn

%description
# Netrc
This library reads and writes
[`.netrc` files](http://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-File.html).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n netrc-0.10.3
gem spec %{SOURCE0} -l --ruby > rubygem-netrc.gemspec

%build
gem build rubygem-netrc.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
netrc-0.10.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/netrc-0.10.3
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/netrc-0.10.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/Readme.md
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/changelog.txt
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/default_only.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/login.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/newlineless.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/password.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/permissive.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/sample.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/sample_multi.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/sample_multi_with_default.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/data/sample_with_default.netrc
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/lib/netrc.rb
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/test/test_lex.rb
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/test/test_netrc.rb
/usr/lib64/ruby/gems/2.3.0/gems/netrc-0.10.3/test/test_parse.rb
/usr/lib64/ruby/gems/2.3.0/specifications/netrc-0.10.3.gemspec
